### ISSUE TITLE
Channel/User/Playlist input checking

### ISSUE THREAD

**Issue by satyamtg** [openzim/youtube#109]
https://farm.openzim.org/pipeline/5ef9ad429ec57a810576f6e7/debug failed with an error - 
```
OSError: [Errno 36] File name too long: '/tmp/tmphtp8ytv7/cache/channel_PLr5n3ojAJWjSVnG_EK1xF3rW1Lo0N2qwA,PLr5n3ojAJWjQEiRIuHlRoN7rBDKG6GbvH,PLr5n3ojAJWjRGQ1DnnIqDrIXKuuNydGid,PLr5n3ojAJWjTkqDW49ew1u7vsbVzM5Uub,PLr5n3ojAJWjSVh9mgusLb6npGNnFif_Sw,PLr5n3ojAJWjRSuu4s5Vu1CEN0rkgXZ-VA,PLr5n3ojAJWjRDmRmIVAsD4MSEt7wMSOGr,PLr5n3ojAJWjSNVp6jrlwXPz5MyFArv6oO,PLr5n3ojAJWjRiuPrUAAveWrrqnNPPNzYK.json'
```
This is due to the JSON name being the same as the --id tag it seems.

**Comment by rgaudin** [comment]
This is an incorrect recipe. Recipe states that this is a `channel` and provides a list of playlists as `ID`.

The auto-name/filename feature constructs a name/filename based on the `channel` ID which, in this case, is incredibly long and incorrect.

Channels are usually 24chars long, so we should exit and warn should a user launch a `channel` request with an ID longer than that but that's just for usability improvements.

**Comment by DevanshD3** [comment]
Hey I am new to open source community , could you please explain the issue ? I didn't quite understand it
