### ISSUE TITLE
Ubungo scraping seems broken

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#116]
https://farm.openzim.org/pipeline/5f3e1e3c5684802b4624a4a5/debug

**Comment by rgaudin** [comment]
Should you have read the error message, you'd seen it's a recipe mistake 😉

**Comment by kelson42** [comment]
@rgaudin It was working and I read the error, but was not sure what to do. I kind of assume you would have done the migration. Looks like you fixed the recipe... but it still fails, see https://farm.openzim.org/pipeline/5f3e64525684802b4624b38e/debug.

**Comment by rgaudin** [comment]
Still a recipe error. Fixed and relaunched, running now.
