### ISSUE TITLE
Video poster is not displayed anymore properly on IPad iOS

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#125]
Here an exemple with the browser:
![B6A25CA2-5E53-4580-BF2B-7A36BD2FC185](https://user-images.githubusercontent.com/1029718/94337963-bc9e1f00-ffee-11ea-93c3-ea922e8627f3.png)

Same problem in Kiwix for IOS.

Probably a consequence of webp introduction

**Comment by rgaudin** [comment]
hum, that has been specifically tested. Is the zim from latest youtube ? Is the browser firefox?

**Comment by kelson42** [comment]
Yes and yes

**Comment by kelson42** [comment]
http://library.kiwix.org/astrolabe_fr_all_2020-09/M/Scraper

**Comment by rgaudin** [comment]
It's #126
