### ISSUE TITLE
WebP polyfill error on welcome poster

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#128]
At least on [skin-of-color-society](https://farm.openzim.org/recipes/skin-of-color-society_en_all) the welcome poster is not displayed.

Multiple refresh might trigger the following error message and/or make the poster appear. This tend to point to a loading issue. It may be that we're calling the polyfill too early after the code that injects the video details on top and (more importantly) the videojs call that transforms this node into the video player.

```
[Error] Unhandled Promise Rejection: e: webp image polyfill failed for url "http://localhost:9999/skin-of-color-society_en_all_2020-10/I/videos/lDgUCN4IuY0/video.webp": e: failed to polyfill image "http://localhost:9999/skin-of-color-society_en_all_2020-10/I/videos/lDgUCN4IuY0/video.webp": failed to decode webp image: undefined is not an object (evaluating 'o.asm.stackSave')
	(anonymous function) (webp-hero.bundle.js:1:985679)
	(anonymous function) (webp-hero.bundle.js:1:985719)
	s (webp-hero.bundle.js:1:984479)
	promiseReactionJob
```

**Comment by gajanangitte** [comment]
the CHANGELOG showed some fixes made to WebP for apple poly-filling. is this issue still open to work on? would it be solved if we delay the trigger_web_polyfill function by a second? please guide me on this issue

**Comment by kelson42** [comment]
AFAIK the issue is still valid but the rootcause is unknown, you should try by yourself a solution.

**Comment by kelson42** [comment]
@rgaudin Considering that now all modern Web browsers support Webp image format:
* The user impact should near to zero
* It will be hard to debug it

I wonder if we should keep this ticket open?
