### ISSUE TITLE
UnboundLocalError: local variable 'meta' referenced before assignment

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#139]
[download] Destination: /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.f251.webm

[download]   0.0% of 19.67MiB at 405.05KiB/s ETA 00:49
[download]   0.0% of 19.67MiB at  1.16MiB/s ETA 00:17
[download]   0.0% of 19.67MiB at  2.67MiB/s ETA 00:07
[download]   0.1% of 19.67MiB at  5.64MiB/s ETA 00:03
[download]   0.2% of 19.67MiB at  2.10MiB/s ETA 00:09
[download]   0.3% of 19.67MiB at  2.71MiB/s ETA 00:07
[download]   0.6% of 19.67MiB at  3.60MiB/s ETA 00:05
[download]   1.3% of 19.67MiB at  5.44MiB/s ETA 00:03
[download]   2.5% of 19.67MiB at  8.77MiB/s ETA 00:02
[download]   5.1% of 19.67MiB at 14.54MiB/s ETA 00:01
[download]  10.2% of 19.67MiB at 24.86MiB/s ETA 00:00
[download]  20.3% of 19.67MiB at 25.95MiB/s ETA 00:00
[download]  40.7% of 19.67MiB at 30.64MiB/s ETA 00:00
[download]  49.6% of 19.67MiB at 28.05MiB/s ETA 00:00
[download]  49.6% of 19.67MiB at 416.76KiB/s ETA 00:24
[download]  49.6% of 19.67MiB at  1.19MiB/s ETA 00:08
[download]  49.6% of 19.67MiB at  2.73MiB/s ETA 00:03
[download]  49.7% of 19.67MiB at  5.78MiB/s ETA 00:01
[download]  49.8% of 19.67MiB at  2.10MiB/s ETA 00:04
[download]  49.9% of 19.67MiB at  2.59MiB/s ETA 00:03
[download]  50.2% of 19.67MiB at  3.58MiB/s ETA 00:02
[download]  50.9% of 19.67MiB at  5.24MiB/s ETA 00:01
[download]  52.1% of 19.67MiB at  8.46MiB/s ETA 00:01
[download]  54.7% of 19.67MiB at 14.15MiB/s ETA 00:00
[download]  59.8% of 19.67MiB at 24.26MiB/s ETA 00:00
[download]  69.9% of 19.67MiB at 30.94MiB/s ETA 00:00
[download]  90.3% of 19.67MiB at 35.36MiB/s ETA 00:00
[download]  98.8% of 19.67MiB at 35.40MiB/s ETA 00:00
[download]  98.8% of 19.67MiB at 438.87KiB/s ETA 00:00
[download]  98.8% of 19.67MiB at  1.25MiB/s ETA 00:00
[download]  98.9% of 19.67MiB at  2.87MiB/s ETA 00:00
[download]  98.9% of 19.67MiB at  6.03MiB/s ETA 00:00
[download]  99.0% of 19.67MiB at  2.09MiB/s ETA 00:00
[download]  99.1% of 19.67MiB at  2.67MiB/s ETA 00:00
[download]  99.5% of 19.67MiB at  3.56MiB/s ETA 00:00
[download] 100.0% of 19.67MiB at  5.10MiB/s ETA 00:00
[download] 100% of 19.67MiB in 00:00
[ffmpeg] Merging formats into "/output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.webm"
Deleting original file /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.f244.webm (pass -k to keep)
Deleting original file /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.f251.webm (pass -k to keep)
[zimscraperlib::2021-01-11 02:18:34,602] INFO:Encode /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.webm -> /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.webm video format = .webm
[youtube2zim::2021-01-11 02:31:44,534] DEBUG:Uploading video file for Ouy2ocDbFYs to cache ...
[youtube2zim::2021-01-11 02:31:49,370] ERROR:webm/low/Ouy2ocDbFYs failed to upload to cache: Failed to upload /output/tmpobb8pd_4/videos/Ouy2ocDbFYs/video.webm to org-kiwix-youtube/webm/low/Ouy2ocDbFYs: An error occurred (TemporarilyUnavailable) when calling the CreateMultipartUpload operation (reached max retries: 4): Maximum number of server active requests exceeded
[youtube2zim::2021-01-11 02:31:49,370] DEBUG:Attempting to download thumbnail for Ouy2ocDbFYs from cache...
[youtube2zim::2021-01-11 02:31:58,227] ERROR:FAILED. An error occurred: local variable 'meta' referenced before assignment
[youtube2zim::2021-01-11 02:31:58,227] ERROR:local variable 'meta' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/entrypoint.py", line 202, in main
    scraper.run()
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/scraper.py", line 294, in run
    succeeded, failed = self.download_video_files(
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/scraper.py", line 506, in download_video_files
    return self.download_video_files_batch(options, self.videos_ids)
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/scraper.py", line 698, in download_video_files_batch
    if self.download_video(video_id, options) and self.download_thumbnail(
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/scraper.py", line 651, in download_thumbnail
    if self.download_from_cache(s3_key, thumbnail_path, preset.VERSION):
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.12-py3.8.egg/youtube2zim/scraper.py", line 564, in download_from_cache
    if not self.s3_storage.has_object_matching_meta(
  File "/usr/local/lib/python3.8/site-packages/kiwixstorage-0.4-py3.8.egg/kiwixstorage/__init__.py", line 430, in has_object_matching_meta
    return meta.get(tag) == value
UnboundLocalError: local variable 'meta' referenced before assignment

In c’est pas sorcier recipe https://farm.openzim.org/pipeline/0cb0223bedd943b9b7537ff5/debug

**Comment by rgaudin** [comment]
upstream bug https://github.com/kiwix/python_storagelib/issues/5
