### ISSUE TITLE
Dependence conflict

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#146]
https://farm.openzim.org/pipeline/b5705aee272fec43dfbc1606/debug

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
youtube2zim 2.1.13 requires requests<=2.24,>=2.23, but you have requests 2.25.1 which is incompatible.

**Comment by rgaudin** [comment]
Fixed this error message in c0a2aab but it's not the cause of this recipe's failure (403).
