### ISSUE TITLE
`<video>` (possibly also `<audio>`) tags are missing the attribute `controls` in Khan Academy ZIM

### ISSUE THREAD

**Issue by Jaifroid** [openzim/youtube#150]
At least in Khan Academy ZIMs, ~~possibly also in recent TED talks~~ (EDIT: only in Khan Academy), the `<video ... >` container no longer has the attribute `controls`. For more discussion of this, see: https://github.com/kiwix/kiwix-js/issues/760 .

The missing attribute means that in readers which do not use `video.js` or `ogv.js` (Kiwix JS in jQuery mode, for example, which cannot run JS from the ZIM), the controls are now hidden, and clicking the video does not start playing it. A user would need to know that they have to right-click the video and choose "Show controls...", but this is not obvious.

To be clear, there is JS code in a dataset property that sets `controls=true` in JS (probably in `video.js`), but this can't be read by Kiwix JS in jQuery mode.

It's important to allow basic HTML5 playback to continue to work for browsers that natively support WebM or MP4, without needing the JS player.

**Comment by kelson42** [comment]
If this is confirmed we probably should consider a fix in all other scrapers embedding videos. We have many of them.

**Comment by Jaifroid** [comment]
My test ZIM is: `khan-academy-videos_en_special-relativity-physics-khan-academy_2021-03.zim`. A PR fixing it in KiwixJS reader is here: https://github.com/kiwix/kiwix-js/pull/761 . I know that TED zims always (used to) play fine in Kiwix JS jQuery mode, but I haven't yet tested on a very recent one, so it could be either a local issue with the Khan Academy ZIM as of March 2021, or it could be a wider issue.

**Comment by Jaifroid** [comment]
I've now managed to download `ted_en_global_issues_2021-08.zim`, which is from last month. The issue does **not** exist in that ZIM. So either it was fixed between 2021-03 and now, or else it is specific in some way to Khan Academy scrapes.

**Comment by rgaudin** [comment]
TED uses the ted scraper while those khan videos uses youtube one. we should expect to fix this in most scrapers with video.
