### ISSUE TITLE
Unable to scrape long videos

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#153]
Probably following up on #149 : I have been trying to scrape a movie off youtube ([recipe here](https://farm.openzim.org/recipes/bluetown-movies-1_en)) to no avail for the past two weeks. The workers get blacklisted after a few hours of work (target movies were about 90 minutes long)

**Comment by rgaudin** [comment]
Not related to #149. That ticket is about API request which has nothing to do with this.

Then is nothing we can do at the scraper level about this. Trying to run it on a worker which haven't done any youtube in a little while and making sure it's the single youtube recipe (using the platform limitation) would increase the chances of it passing.

**Comment by Popolechien** [comment]
Waiting for PR to be merged on youtube-dl

**Comment by kelson42** [comment]
@rgaudin Considering that we don't use youtube-dl anymore, what is the status of this ticket?

**Comment by rgaudin** [comment]
Looks like @Popolechien reopened this ticket because I fixed it with the hidden patch and he was expecting us to close this upon upstream merge?? Or maybe it was just an accident :)

Anyway, we don't use it anymore and this issue is obsolete.
