### ISSUE TITLE
Remove inline javascript to comply with some CSP

### ISSUE THREAD

**Issue by mossroy** [openzim/youtube#154]
Tested with dirtybiology_fr_all_2021-10.zim, dirtybiology_fr_all_2015-11.zim, and litterature-audiobooks-poetry_fr_2020-01.zim

Every page has the following inline script, that could be moved to a javascript file:

`<script>$(document).ready(function() { trigger_webp_polyfill(); });</script>`

And the drop-down list of the home page does not work because of its onchange attribute, that could be replaced by attaching an event handler on it (in a javascript file):

`<select class="chosen-select" name="list" onchange="genplaylist()">...</select>`

**Comment by rgaudin** [comment]
Fixed via 5d468e3. Tested OK with Kiwix JS 3.4.0 extension in Chrome; which failed without the fix.

**Comment by mossroy** [comment]
Thanks!
Could you give us a link to a newly-generated ZIM file (when one is available)?

**Comment by rgaudin** [comment]
A new [biologie-tout-compris_fr_all](https://farm.openzim.org/recipes/biologie-tout-compris_fr_all) is scheduled but in the mean time, here's the test one I created [test_yt5_2022-07.zim](https://www.grosfichiers.com/L3NZPT9VPWk) (16MB)

**Comment by rgaudin** [comment]
Here's a real one: https://mirror.download.kiwix.org/zim/videos/hygiene-mentale_fr_all_2022-08.zim

**Comment by mossroy** [comment]
It seems to work fine, thanks!
