### ISSUE TITLE
youtube-dl version not usable anymore

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#159]
Just [ran a recipe](https://farm.openzim.org/pipeline/d2ed10d0a26b4df468d7be26/debug) and got the following error message `youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name;`

**Comment by rgaudin** [comment]
Thank you ; we're still using a december-old patched youtube-dl version (with the speed fix). Seems like online YT isn't compatible with it anymore. I'll latest youtube-dlp to see if the speed issue has been resolved.

**Comment by rgaudin** [comment]
Fixed by 7a2a0eb ; Speed wasn't an issue with my minimal tests but we'll see on the zimfarm. I've moved all youtube recipes to `dev`. I've [restarted that recipe](https://farm.openzim.org/pipeline/f37020d79a3ed875a51dce26). Let's test this one and other and make a release if that's satisfying.
