### ISSUE TITLE
Latest biologie-tout-compris is really big

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#163]
Ariund 20x bigger than past versions https://farm.openzim.org/pipeline/f81420d79a3ed875b376de26

Really not clear why.

**Comment by rgaudin** [comment]
2022-04 had 26 videos ; this one has 153.

Keep in mind that channels are a collection of playlists which themselves can contain user-created videos or other videos so such a huge increase in 3 months might be just new curated playlists

**Comment by kelson42** [comment]
OK, closing, I don't have really the time to investigate and this is probably legit.
