### ISSUE TITLE
Enable subtitles

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#164]
I'm looking at [Crash Course videos](https://library.kiwix.org/crashcourse_en_all_2022-07) and see that subtitles are not available. 

Looking at past issues however it looks like they should be available. Is it because an option should be enabled in the recipe (as hinted in #38 )?

**Comment by rgaudin** [comment]
Looks like a bug but since we changed the third-party library, we'd need to relaunch it. Don't do it just now, I am opening a ticket affecting subtitles (found investigating this) that needs to be resolved first

**Comment by rgaudin** [comment]
restarted it ; we'll see.

**Comment by rgaudin** [comment]
Not sure what happened for that ZIM but it's now working. 
<img width="609" alt="Screenshot 2022-11-08 at 13 01 16" src="https://user-images.githubusercontent.com/57929/200571849-75234818-821c-4285-9016-97f94664296a.png">

ZIM update [is in progress](https://farm.openzim.org/pipeline/1c22d98722055da87764a636) but it's a large ZIM so it may take some time

**Comment by rgaudin** [comment]
You can see it live at http://library.kiwix.org/crashcourse_en_all_2022-11/the_nucleus_crash_course_chemistry_1.html
