### ISSUE TITLE
Incorrect error code

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#166]
In this run, a playlist request is launched and returns `0` but seems to have failed (output is not known as it ws *successful*) and produced no ZIM.

https://farm.openzim.org/pipeline/7edb0a33987bbbb317e95336/debug

**Comment by kelson42** [comment]
Still no zim produced https://farm.openzim.org/pipeline/b08bb9f49e7c6f85b3219636

**Comment by rgaudin** [comment]
Was a recipe issue: ZIM filename was set without a `.zim` suffix so ZIM file was properly created but never uploaded by zimfarm worker.

Two things we can do at zimfarm level:
- make the UI fail on missing suffix for this field. We already do it somewhere else but each offliner has its own definition.
- Mark the task as failed if no ZIM file was produced (or uploaded, as already suggested)
