### ISSUE TITLE
Release 2.1.18

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#168]
- [x] Use latest version of python-scraper lib
- [x] Update the Changelog
- [x] Close current milestone and create new one incrementaly (_a priori_ a minor version)
- [x] Create a tag on git
- [x] Secure new version is published on https://hub.docker.com/r/openzim/sotoki and Github
- [x] Update the Github release with the Changelog
- [ ] Create new empty entry in Changelog (placeholder for future entries)
- [ ] Advertise this new version

**Comment by holta** [comment]
_Awesome:_

Thanks all for this critical community tool!

**Comment by kelson42** [comment]
@holta #34 has been closed, #722 actually belongs to `openzim/zimfarm` and #155 will be fixed in the next days.
