### ISSUE TITLE
Playlist scraping does not "slug" properly in the ZIM filenames

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#169]
Look at how the ZIM filenames of https://farm.openzim.org/recipes/zenius_id_playlists look like:
https://farm.openzim.org/pipeline/46001c89460732f50a144a36

They don't respect the norm, and actually I suspect that if the playlist name has a character which is not supported by the filesystem then it will crash.

**Comment by rgaudin** [comment]
The recipe is setting the Name via playlists-name using a dynamic variable. This is likely not a very good Name and definitely not convention OK ; but this is a known and tricky problem regarding that specific YT feature

I suppose we could slug whatever value we have when setting the filename (even if a filename was passed) ; in all scrapers (not just this one). that would be safer and mostly harmless.


And yes, we'll probably not encounter much filename issue when creating as we're on ext4 and xfs but users on Windows for instance might have difficulties downloading (I suppose the browser fixes it but I don't really know)

**Comment by benoit74** [comment]
@kelson42 now that we've agreed we will stop to encourage using dynamic metadata and will even stop using it in our Zimfarm, is there really something left to be done here?

**Comment by kelson42** [comment]
@benoit74 Not sure myself, but I would recommend to secure that filename can be written to the fs.

**Comment by dan-niles** [comment]
> Look at how the ZIM filenames of https://farm.openzim.org/recipes/zenius_id_playlists look like:
> https://farm.openzim.org/pipeline/46001c89460732f50a144a36

@kelson42 Could you please clarify what needs to be done here? The links provided above seem to be broken, so it's a bit unclear what needs to be fixed.

If the issue is with the ZIM filename, we are already using `validate_zimfile_creatable` from [python-scraperlib](https://github.com/openzim/python-scraperlib/blob/335d5271e106b374f1aca871d19557ff2c81582d/src/zimscraperlib/zim/filesystem.py#L257) to ensure the ZIM file is creatable with the given name.

**Comment by kelson42** [comment]
@dan-niles This was a playlist based recipe and the bug is very old.To me the situation is not that clear but we don't need this feature anyway and this woujd be hard to reproduce it - if possible at all. I will clise it.
