### ISSUE TITLE
Video viewer should allow change of reading speed

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#174]
Many players allows their users to modify the video reading speed, either more slowly to ease comprehension or faster for speed-viewing (e.g. 0.75x - 1.25x)

**Comment by benoit74** [comment]
https://github.com/openzim/youtube/pull/229 suggests to propose 0.25, 0.5, 1, 1.5, 2 as reading speeds in ; @dan-niles could you explain why you chose these values?

@Popolechien these are the reading speed that will be available in the video player, is that ok for you?

**Comment by dan-niles** [comment]
I just wanted to make it more similar to what YouTube offers, ranging from 0.25x to 2x. 

Additionally YouTube also provides 0.75x and 1.75x, so I can also include those if needed. So the playback rates would be: [0.25, 0.5, 0.75, 1, 1.5, 1.75, 2]

**Comment by Popolechien** [comment]
7 different speeds? Seems a lot to me but who are we to question their choices ¯\_(ツ)_/¯

**Comment by benoit74** [comment]
Then we are all OK to keep only 5 choices?

**Comment by benoit74** [comment]
OK, so let's use `0.25, 0.5, 1, 1.5, 2`  for now, and we'll see if this is a problem.
