### ISSUE TITLE
Upgrade python-scraperlib to 3.x, including CLI support for description / long_description flags

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#175]
See https://github.com/openzim/overview/issues/21

**Comment by dikshant182004** [comment]
I hope this message finds you well. I'm Dikshant jha and I am eager to contribute to this open-source issue. After reading the project and its documentation, I think this can be the right fit as a  potential task to work on as my first contribution.

I am new to open-source contributions, and I would greatly appreciate your mentorship and guidance as I get started. 
If you have some time, could we schedule a brief chat or exchange messages to discuss this further? I'm eager to learn and contribute to the project's success.

Thank you for considering my request. I look forward to your response

**Comment by benoit74** [comment]
Thank you @dikshant182004 for your proposition to help. I will contact you on Slack, it will be easier to discuss there.

**Comment by dikshant182004** [comment]
okay, Let's discuss on slack

**Comment by benoit74** [comment]
We must also update Jinja2 at the same time, and get rid of markupsafe explicit version.

**Comment by benoit74** [comment]
And check if `if not isinstance(html, str):` in `render_template` is still needed.

**Comment by benoit74** [comment]
And upgrade to Python 3.11 (or 3.12 if zimscraperlib has been updated to support it)

**Comment by benoit74** [comment]
Cannot be done before https://github.com/openzim/youtube/issues/186 is solve. Otherwise, many zimfarm recipe will fail due to invalid metadata.
