### ISSUE TITLE
Madrasa channel recipe failure

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/youtube#176]
This recipe is failing for long time
https://farm.openzim.org/recipes/madrasa

I tried all the large content APIs with no success, changed the parameter channel to user with no success.
Please check.

**Comment by rgaudin** [comment]
- “is failing” is not much useful
- “for long time”: what has been done to circumvent it?

I see that the recipe **never worked** and never lasted more than 20 seconds. This mean it fails to even start. It should have been disabled then.

If you look at the log it says `ERROR:Invalid username `Madrasa`: Not Found`

I've checked and indeed it's a `youtube` scraper issue. We cant seem to query this channel via the API using its name. It looks like a bug/limitation of the Youtube API. See #177 

By looking for `channel_id=` in the source code of the YT page, I found its internal id to be `UCq0wtwcAmYtS3VUCgh1BWAg`. Please use this as channelId in recipe.
