### ISSUE TITLE
No sound in Safari

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#181]
On Mac OS 12.7 and Safari Version 17.0 (17616.1.27.111.22, 17616), no sound is produced (even if Safari detects that sound is produced and allows to mute the tab).

I will have a look for upstream issues or open one.

**Comment by benoit74** [comment]
This might have been fixed upstream, because on https://videojs.com/forest sound is working well

**Comment by benoit74** [comment]
Not reproduced on dev machine, sound works fine on same machine when running the scrapper locally.
Was it a temporary issue linked to a change in Youtube / yt-dlp?

**Comment by kelson42** [comment]
Pretty sure this can be fixed by just using latest scraperlib

**Comment by benoit74** [comment]
Closing this for now, we are quite sure it was linked to bad vp8 encoder settings in v1 and we've now upgraded to v2 with https://github.com/openzim/youtube/pull/202
