### ISSUE TITLE
Ensure ZIM metadatas are valid and dynamic in playlists mode

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#186]
In https://github.com/openzim/youtube/pull/185, I had to disable these lines of code:

```
metadata_from JSON file is broken for now
        self.metadata_from = (
            pathlib.Path(self.metadata_from) if self.metadata_from else None
        )
```

This just showed that it is since some times not possible (anymore?) to pass a JSON file with metadata.

Should we fix this?

**Comment by rgaudin** [comment]
We never used it. The feature came from a need of Content team but they never used it because it's too much work (not talking about the additional – but light– burden of publishing it as a JSON file.

Could be handled by CMS ; should be discussed with them but I think we can drop the feature altogether.

**Comment by kelson42** [comment]
This is AFAIK the only way to get proper metadata if multiple ZIM are created in one run? If we remove this feature it should be very clear what we loose and why it has been implemented in a first place. To me, situation is very unclear.

**Comment by kelson42** [comment]
@rgaudin so the feature allows to make youtube zim files with arbitrary videos?

**Comment by rgaudin** [comment]
Sorry I meant individual ZIM/playlist not video 😅

As its name suggests it's for metadata only.

It allows to say Playlist/Zim X has title "I love chocolate" inside the multi playlists channel recipe while with the other method, we can only say that all playlists are named following pattern "Bla-bla-bla {title}" for instance.

It's a good feature but it requires effort from content team and I don't see them using it before we introduce similar feature in CMS. Should be **very easy** to maintain though.

**Comment by benoit74** [comment]
As discussed today during Kiwix weekly meeting, this issue is in fact very important.

We need to devise a solution to set only valid metadata on ZIMs created in playlist mode where one ZIM is created per playlist.

Current solution consisting of using placeholders is useful since it enables the content team to dynamically set the ZIM metadata based on Youtube information instead of using the same metadatas for all ZIMs.

Current solution is however not satisfactory since it surely generate invalid metadatas according to the ZIM spec (typically description and title are too long).

Solving this issue is hence mandatory before upgrading to zimscraperlib 3.x because at this point the lib will refuse to create ZIMs with invalid metadata.

**Comment by benoit74** [comment]
In fact, this is almost a duplicate of https://github.com/openzim/youtube/issues/147. I'm closing this one in favor of the other one.
