### ISSUE TITLE
Harmonize default publisher to `openZIM`

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#192]
As required in https://github.com/openzim/zim-requests/issues/779, the default ZIM publisher must be `openZIM` (mind the case)

**Comment by nida-imran173** [comment]
@benoit74  Should all instances of default publisher be changed from 'Kiwix' to 'openZIM' in scraper.py?

**Comment by benoit74** [comment]
I expect to have only one default value in `entrypoint.py` and this should make its way to the ZIM. I don't know why there are so many default publisher values in `scraper.py`, they should probably be removed. And you should check that the publisher from `entrypoint.py` is passed to the ZIM, default value or customized one with a CLI flag.

**Comment by nida-imran173** [comment]
So basically, the idea is to set only the default publisher value in entrypoint.py for consistency across the project. Correct?

**Comment by benoit74** [comment]
Yep
