### ISSUE TITLE
Illustration does not respect the openZIM specification

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#199]
See for example:
https://farm.openzim.org/pipeline/a021a6b8-019c-498a-b435-f08a3dedac19

Zimcheck report:
 "file_name": "/data/nota-bene_fr_all_2024-03.zim",
  "file_uuid": "1efae61e-9ee7-271d-9120-4bfa0fd892de",
  "logs": [
    {
      "check": "metadata",
      "error": "Illustration_48x48@1 doesn't match regex: ^\\x89PNG\\x0d\\x0a\\x1a\\x0a",
      "level": "ERROR",
      "message": "Illustration_48x48@1 doesn't match regex: ^\\x89PNG\\x0d\\x0a\\x1a\\x0a"
    },

**Comment by rgaudin** [comment]
It's a JPEG image…

**Comment by kelson42** [comment]
If I got is right, using latest scraperlib would help to get that fixed straight, see #175

**Comment by rgaudin** [comment]
Yes, the run would have failed ; and there are conversion functions to use
