### ISSUE TITLE
Scraper is not using logo and banner from the first playlists channel?

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/youtube#200]
Hello, I have an enhancement suggestion that will save time and enhance youtube files quality.
Can we update the Youtube scraper in a way that it scrapes the logo of the channel and the banner automatically from the channel ID while scraping the content?

**Comment by rgaudin** [comment]
It's already the case for channels and playlists have no such thing AFAIK

**Comment by rgaudin** [comment]
Closing ; reopen if I'm missing anything

**Comment by RavanJAltaie** [comment]
Can't we apply the same thing on playlists?
The playlists are coming from a channel, so adding the channel logo and banner would be very useful.

**Comment by rgaudin** [comment]
This issue is not actionable. You need to explain what you would like, and why.

You mention saving time so you can only be talking about ZIM Illustration. Those are already fetched by the scraper. It's from the channel/user or the first playlist's channel.

If you are not only talking about ZIM illustration then describe what you get and what you expect.

**Comment by benoit74** [comment]
@RavanJAltaie could you explain what you don't get and would like to get with current scraper? Is this just a lack of documentation?

**Comment by benoit74** [comment]
@RavanJAltaie should we discuss it live or may I close the issue? We need more details to help you on this

**Comment by RavanJAltaie** [comment]
@benoit74 @rgaudin the scraper is taking the logo and banner if it's a channel.
If it's a playlist, it doesn't. Resulting in a file with no logo and banner, and then we need to enter them manually after checking for files with no logos.

**Comment by benoit74** [comment]
I just checked the code, and I confirm that if it's a playlist (or a list of playlist), scraper is supposed to use the logo and banner of the channel of the playlist (or first playlist in the list if we have multiple playlists).

So this is not a feature request, but a bug report.

I checked one random recipe using a playlist as ID (https://farm.openzim.org/recipes/avanti-alkyhalide/config) and the ZIM has both a logo and a banner (https://library.kiwix.org/viewer#avanti-alkyhalide_2024-03/home.html).

![image](https://github.com/openzim/youtube/assets/7102089/762bdb20-7ce5-41e2-b5f1-9ea351c50b79)

@RavanJAltaie please provide more information on where this is not working so we can help you debug this issue

**Comment by benoit74** [comment]
Nota: the banner is a custom file provided in recipe configuration, I forgot to check that, sorry, but the logo/profile is not specified so it is fetched from online.

**Comment by benoit74** [comment]
Clearing milestone until what's needed is clear

**Comment by benoit74** [comment]
Discussed live, the bug is not there anymore. Closing until a repro arrives
