### ISSUE TITLE
Create a Youtube test channel

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#221]
We should have a test channel for the scraper, with appropriate situations for an end-to-end test of the scraper.

**Comment by benoit74** [comment]
Channel is created at https://studio.youtube.com/channel/UC8elThf5TGMpQfQc_VE917Q
Its name is `openZIM_testing` 
I'm the owner, and I've invited reg as Manager, and dan as Editor.

@dan-niles I let you push appropriate small test videos and create few playlists as needed

After that we should probably modify the readme to mention this test channel as a recommended way to develop the scraper.

**Comment by dan-niles** [comment]
I've uploaded 2 videos and created 2 playlists for now. I'll upload more later based on our testing needs, if needed.

**Comment by benoit74** [comment]
Job's done, we will iterate on content when needed, no need to keep this open.
