### ISSUE TITLE
UI Revamp: Playlist View Page

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#223]
As of now, according to the design proposed whenever a user clicks on a playlist on the "Playlists" page (#214) they are redirected to a "Playlist Player" page (#216). In YouTube, a Playlist has a link below it called "View full playlist" (See fig. 1) which leads to a page that lists all the videos in the playlist. (See fig. 2)

@Popolechien @benoit74 I forgot to include this page in my initial UI proposal. Shall we create a page like this for the new UI?

fig. 1:
<img width="235" alt="image" src="https://github.com/openzim/youtube/assets/56271899/b40bcdc2-9a5b-4066-9900-a5b2f9b009c1">

fig. 2:
<img width="1339" alt="image" src="https://github.com/openzim/youtube/assets/56271899/a16c0867-49df-44a4-b1d1-4a6d65d9cc29">

**Comment by benoit74** [comment]
@kelson42 your PoV is welcomed as well

From my perspective, I don't have much to say other than ask another question: should we plan this for the end of the GSoC or later as a "nice-to-have"?

**Comment by kelson42** [comment]
I'm in Favorit

**Comment by Popolechien** [comment]
I would say it's a nice-to-have but definitely not priority. A lot of Youtube zims are just playlists (as opposite to entire channel), so this would not cover all use cases.
