### ISSUE TITLE
Welcome page "video" seems to not autoplay properly

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#23]
This seems to be a new bug, but the first time you load the welcome page of any "youtube" ZIM file, then the top welcome video spinner just run bug nothing happens.

I see the error ```Array [ "Video Error", Object ]``` in the javascript dev console.

I can reproduce that bug with:
* teded_en_all_2017-10.zim
* tedmed_en_all_2017-10.zim

But if I change to a sub-cateogry (top right select box) and then come back to the default one (--) then it works. So, the video is there... but for some reason it is not played properly.

Tested with last nightly version of kiwix-serve.

**Comment by dattaz** [comment]
Normally this bug is now fixed

**Comment by kelson42** [comment]
Maybe worth a new try with a nightly of kiwix-serve.

**Comment by dattaz** [comment]
Yes, I try today, and a go with this conclusion : 
I can reproduce in Firefox 62 (nightly) with kiwix-serve 0.10. Not with chromium or (Firefox 62 and a previous build of kiwix-serve) (which one?)
I am still investigating
