### ISSUE TITLE
Setup ogv.js as a fallback in video.js

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#230]
The html5 player in `video.js` is currently used for video playback. However, to support older browsers like Safari for playing webm videos, we need to set up `Ogv.js` as a fallback.

However, there is an issue with integrating Ogv.js into the Vue.js app. In the [ogvs](https://github.com/openzim/youtube/tree/ogvjs) branch, I attempted to configure the [videojs-ogvjs](https://github.com/hartman/videojs-ogvjs) plugin, but encountered an error in the console:

```
TypeError: Cannot read properties of undefined (reading 'getComponent')
```

It seems that the videojs-ogvjs plugin is attempting to access video.js in a global scope but is unable to locate it.

**Comment by benoit74** [comment]
@rgaudin does it reminds you something?

**Comment by benoit74** [comment]
(Dan is struggling to setup ogv.js / videojs-ogvjs in the new Vue.JS app)

**Comment by rgaudin** [comment]
We've never used it inside a Vue.js app. Check first that it's working as expected outside of Vue if not already done.

I think the plugin was outdated at some point and even slightly patched but I don't know if that is still required.
I see that I have [a gist](https://gist.github.com/rgaudin/94d8f916d6d9c83f9b9ca86f6d89dc18) of it.

Might simply be that Vue is restrictive and the plugin is not compliant.

**Comment by benoit74** [comment]
OK, thank you.
What Dan has discovered so far (I let you confirm) seems to be more linked to a timing issue / compatibility issue with Vite. You're right it has most probably nothing to do with Vue.

**Comment by benoit74** [comment]
See discussion in https://github.com/openzim/overview/issues/36 also
