### ISSUE TITLE
Revisit support of Picture-in-Picture

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#231]
In 2020, https://github.com/openzim/youtube/pull/92 concluded that picture-in-picture button of video.js had to be hidden due to bad support in multiple readers / browsers.

4 years later, it is probably now time to check again if the issues we faced at that time are still present. Picture-in-picture was quite young at that time, it might have evolved significantly since then.

We need to create a small ZIM with only one video served with a video.js player with PIP button enabled. This ZIM does not need to be created with Youtube scraper at all. And then we need to test this ZIM on our readers to confirm if the landscape has changed or not.

**Comment by kelson42** [comment]
I'm only familiar with PiP in iOS. On iOS, from Kiwix 3.4.0, it works perfectly using standarts OS workflows/gestures. Thetefore, I'm not sure anything else (a button) is needed. But ready to test one if needed.

**Comment by kelson42** [comment]
@benoit74 Could we have an example ZIM to test?

**Comment by benoit74** [comment]
Still not working on kiwix-apple, still not really needed because anyway most browsers / readers adds their own button. Closing this as "won't do".
