### ISSUE TITLE
New UI: Remove side margins in UI for tablet screens

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#252]
Currently on tablet screens there are margins on the left and right side of the UI. These are good to have on large monitors so that the UI is always centered on the screen, but for medium sized screens like tablet screens, this is a waste of space. 

I propose we remove these margins so that more content is visible on tablet screens.

With margins on tablet screen (Current UI):
<img width="400" alt="image" src="https://github.com/openzim/youtube/assets/56271899/0efa18e6-b03d-4821-9067-30ab9c82abdf">
<img width="400" alt="image" src="https://github.com/openzim/youtube/assets/56271899/fccb98e4-6f30-40a0-97da-a987ffe78f5c">

Without margins on tablet screen (Proposed UI):
<img width="400" alt="image" src="https://github.com/openzim/youtube/assets/56271899/7d5ab859-1b29-4c94-9c2d-fd92d7717e51">
<img width="400" alt="image" src="https://github.com/openzim/youtube/assets/56271899/b1d06986-45b6-42a9-871f-0a37a11a11d4">

**Comment by benoit74** [comment]
Good for me, any remark @Popolechien?

**Comment by Popolechien** [comment]
Nope, LGTM
