### ISSUE TITLE
Test the new scraper on existing Zimfarm recipes

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#261]
Up to now, we've been developing the scraper and testing it with the [openZIM_testing](https://www.youtube.com/channel/UC8elThf5TGMpQfQc_VE917Q) YouTube channel. It would be beneficial if we could test it on actual Zimfarm recipes to ensure the new scraper meets all the requirements.

@Popolechien Could you share a few (2-5) Zimfarm recipes to test out the new YouTube scraper? I believe it would be helpful to test and ensure everything is working correctly with the new scraper.

**Comment by benoit74** [comment]
I suggest to start with [deus-ex-silicium_fr_all](https://farm.openzim.org/recipes/deus-ex-silicium_fr_all) which has just been rebuilt. This is a significantly big channel, with multiple playlists and where current UI is clearly clumsy.

We should probably simply reconfigure the recipe to use `dev` Docker image and push to dev library.

**Comment by Popolechien** [comment]
The Canadian prepper playlists are good ones to try our hand at: 
https://farm.openzim.org/recipes?tag=youtube&name=canadian_prepper

**Comment by benoit74** [comment]
@RavanJAltaie @Popolechien 
I'll transition https://farm.openzim.org/recipes/deus-ex-silicium_fr_all and https://farm.openzim.org/recipes/canadian_prepper_bugoutroll_en to the `dev` image and pushing to the `dev` library to test the new ZIM UI.
I will do the same with other canadian prepper once titles have been fixed and a new ZIM has been produced with the old UI (see my message on Slack).
Please do not touch anymore these recipes until further notice (and do not use these recipes as clone source when cloning a recipe to create a new Youtube recipe, since the new Youtube UI is not yet ready for production, so you shouldn't publish ZIM from `dev` image to production).

**Comment by benoit74** [comment]
Two first ZIMs have been produced today:
- https://dev.library.kiwix.org/viewer#canadian_prepper_bugoutroll_en_2024-07
- https://dev.library.kiwix.org/viewer#deus-ex-silicium_fr_all_2024-07

**Comment by Popolechien** [comment]
This looks very, very good.

Question: the Canadian Prepper zim is that of a single playlist. Shouldn't the playlist tab be disabled in that case?
Also, I see the banner is missing in CP, and replaced by a grey-black one for Deus ex. Bug or feature?

Also: `About channel` -> `About`or `About this channel`

**Comment by dan-niles** [comment]
@Popolechien 
> Question: the Canadian Prepper zim is that of a single playlist. Shouldn't the playlist tab be disabled in that case?

Sure, if there's only 1 playlist in the ZIM we can hide the playlist tab. I'll update the UI.

> Also, I see the banner is missing in CP, and replaced by a grey-black one for Deus ex. Bug or feature?

Feature I guess 😅
If no banner image is provided, the scraper defaults to picking a `main-color` from the profile picture. In the [Zimfarm recipe](https://farm.openzim.org/pipeline/8a7fae13-d7f7-4a4d-bc39-8927ffa24b85/debug) for CP, the `main-color` is set to white, so the UI displays a white banner. 
(It's better to set a different `main-color` in the recipe or let the scraper automatically pick the color in this case)

For Deus-ex the banner color is picked from the profile picture since `banner-url` and `main-color` are not provided.

**Comment by kelson42** [comment]
I'm very positively impressed by this first demonstration. Keep going that way!
