### ISSUE TITLE
Update compatibility matrix wiki page

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#273]
The [compatibility matrix](https://github.com/openzim/youtube/wiki/Compatibility) wiki page needs to be revisited and updated for the new scraper changes.

**Comment by benoit74** [comment]
@rgaudin do we really need this compability matrix anymore? AFAIK, all issues mentioned have now been fixed

**Comment by benoit74** [comment]
This is not a blocking point for 3.0.0 ; @rgaudin any insight to share?

**Comment by kelson42** [comment]
@benoit74 We should delete the page and close this issue.

**Comment by benoit74** [comment]
OK, thank you

**Comment by benoit74** [comment]
Done
