### ISSUE TITLE
Video playback not working on Safari 10.1

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#274]
Video playback is not working on `Safari 10.1` with both the new scraper and v2 scraper.

New Scaper:
Video doesn't load. The error thrown says "No compatible source was found for this media."
![image](https://github.com/user-attachments/assets/fd98e2cc-965b-47ed-987f-4969f65d2795)

V2 Scraper:
Video doesn't load. Player remains with a black screen. No errors are thrown on the console.
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/4f22a93c-23f4-4002-a1e1-25ffc1cac56e">

**Comment by kelson42** [comment]
A regression?

**Comment by kelson42** [comment]
This is a very old version of Safari (2016). Unfortunately we can not support such an old version.
