### ISSUE TITLE
Upgrade video.js version to fix issue with minification on Chrome 51-59

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#275]
As mentioned in https://github.com/openzim/youtube/pull/272#issuecomment-2244250370, once video.js releases a new version with the https://github.com/videojs/video.js/pull/8810 patch we should update video.js in the zimui and check if video playback works on Chrome 51-59.

**Comment by benoit74** [comment]
New version is ready, see https://github.com/videojs/video.js/pull/8810#issuecomment-2277376009

@dan-niles could you test this so that we include it in the soon coming 3.0.1 release?

**Comment by benoit74** [comment]
Oh no, it is not yet published on NPM, we still have to wait a bit

**Comment by dan-niles** [comment]
I tested out video.js `v8.17.3`. Good news is the UI is finally loading in Chrome `v59-52`. (Chrome 51 is still not working)
- Everything (UI + Video playback) works fine on Chrome `v59` and `v58`. 
- On Chrome `v57-52` the thumbnails are not loading and video.js displays an error as shown below. Sometimes when I reload the page the video playback works.
<img width="477" alt="image" src="https://github.com/user-attachments/assets/daa99a2b-657e-4d7f-a854-dfe486256de5">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/ccc0ecd1-e853-40a6-acd7-d4b7c093d8b4">
This needs to be investigated further.

**Comment by dan-niles** [comment]
Opened #291 to track this seperately.
