### ISSUE TITLE
Add nice overlay on banner

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#279]
When no banner image is used, only a single color is used. When color is white or close to white, it makes a weird gradient. 

![image](https://github.com/user-attachments/assets/ba852bfd-9483-42f4-add3-0f3531b4cebc)

In some old browsers, the gradient does not even load.

It would be nice to have some kind of overlay pattern to make the banner visible in all situations and limit the "weirdness" of this part of the UI under all circumstances.

**Comment by dan-niles** [comment]
I tried a couple of backgrounds from https://www.magicpattern.design/tools/css-backgrounds. I like the first one. @Popolechien @benoit74 WDYT?

Wavy:
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/1dbe87db-09f0-494d-849e-2b8df32a2b26">

Zigzag 3D:
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/8d6f585e-6fbc-4af7-986e-41a5383220ff">

Isometric:
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/91ea9138-8f7f-4ce0-af0c-a4f53437cb4e">

Polka:
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/c1037fab-6fb0-41cf-8b04-05c3f3e2eda1">

**Comment by dan-niles** [comment]
Wavy:
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/bde77388-a015-4e38-9b48-5d61834a7fc3">

Zigzag 3D:
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/474217d9-9568-455a-bdd8-4dddf046bf4d">

Isometric:
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/ac94bfe3-5307-4fc5-ada7-461412d6a7f3">

Polka:
<img width="1192" alt="image" src="https://github.com/user-attachments/assets/a1ef437c-1b6e-4481-ad87-e992bd57d581">

**Comment by benoit74** [comment]
What we've agreed in our daily meeting is that we will go with zigzag for now. Could always easily be revisited if someone has strong arguments for something else.
