### ISSUE TITLE
feature :: comments in each video on bottom video and description

### ISSUE THREAD

**Issue by chezsick** [openzim/youtube#29]
hello, i an idea, it's to show the comments downloaded on youtube, how to download comments? with the script in python no api ::::::: https://github.com/egbertbouman/youtube-comment-downloader

for to download the comment by video
thank you to add, Sick!

**Comment by kelson42** [comment]
Considering the quality of comments on Youtube in general, I'm quite against this. I see no added value.

**Comment by chezsick** [comment]
ah, is true, with kiwix you have always the high quality, and the option for the feature?

**Comment by rgaudin** [comment]
Shares @kelson42's point of view. Closing as we won't implement this unless there's a large demand. (PRs welcome though).
