### ISSUE TITLE
Document lessons-learned with Youtube v3

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#293]
We should document what we've learned developing Youtube v3, especially everything related to a Vue.JS-based ZIM

This documentation should go on https://wiki.openzim.org/wiki/How-to_create_a_Python_scraper, probably to rewrite / complete ["How_to_develop_a_nice_UI_to_run_inside_the_ZIM" section](https://wiki.openzim.org/wiki/How-to_create_a_Python_scraper#How_to_develop_a_nice_UI_to_run_inside_the_ZIM)

Subjects I have in mind:
- indexing items for suggestion / search
- webp polyfill, beware the lazy loading
- video.JS + webm polyfill
- vite support for old browsers, legacy mode or not

But there is probably many other I forgot about.

**Comment by dan-niles** [comment]
I added the content to https://wiki.openzim.org/wiki/How-to_create_a_Python_scraper and clicked on "Save Changes". It seems like the changes went live. 

Isn't there a review process when an edit is submitted? Do the changes just go live immediately? 😅

**Comment by rgaudin** [comment]
> Isn't there a review process when an edit is submitted? Do the changes just go live immediately? 😅

No there's no such thing.

**Comment by benoit74** [comment]
Thank you, nothing much to add at this stage, thank you!
