### ISSUE TITLE
URLs are not unique anymore in version 3.0

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#297]
This is a very serious regression which should be fixed in priority

**Comment by benoit74** [comment]
Could you please be more specific? I'm sorry but I don't get what's wrong

**Comment by kelson42** [comment]
@benoit74 It seems this is a bug in kiwix serve.... but actually I was not able to find one already open.

**Comment by benoit74** [comment]
Let's close this in favor of newly created issue then: https://github.com/kiwix/libkiwix/issues/1120
