### ISSUE TITLE
Port youtube-dl to youporn

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#30]
It looks like the UK is going to mandate ID disclosure in order for net users to browse p0rn. For individuals that have legitimate concerns about their privacy, the possibility of downloading such videos for offline consumption might be interesting.

Notwithstanding legal concerns, what would at this stage be the technical impediments to converting, say, Youporn videos to the zim format?

**Comment by rgaudin** [comment]
This ID disclosure thing have been abandoned as far as I can tell.

The scraper is now youtube-specific. I'm closing this until demand requires it to be reopened.
