### ISSUE TITLE
Sub select videos by date

### ISSUE THREAD

**Issue by blueskiesoky** [openzim/youtube#31]
I would like to be able to run youtube2zim and only gather newer that a certain date.
This would allow splitting a youtube channel zim into smaller parts. Also it would allow creating a new zim for newer content only, without having to modify already downloaded youtube channel zims.

**Comment by kelson42** [comment]
@blueskiesoky Good idea. That should be doable, but I can promise somethin done soin.

**Comment by dattaz** [comment]
Hi,
This is really doable : 
  - Add new option for option parser (https://github.com/openzim/youtube/blob/master/youtube/youtube2zim.py#L9:L16)
  - Add argument to `get_list_item_info` function to pass dateafter
  - Add argument "dateafter" (cf : https://github.com/ytdl-org/youtube-dl/blob/master/README.md#readme), with argument of commande line in this line : https://github.com/openzim/youtube/blob/master/youtube/youtube2zim.py#L47

And that's all i think...

**Comment by blueskiesoky** [comment]
> Hi,
> This is really doable :
> 
> * Add new option for option parser (https://github.com/openzim/youtube/blob/master/youtube/youtube2zim.py#L9:L16)
> * Add argument to `get_list_item_info` function to pass dateafter
> * Add argument "dateafter" (cf : https://github.com/ytdl-org/youtube-dl/blob/master/README.md#readme), with argument of commande line in this line : https://github.com/openzim/youtube/blob/master/youtube/youtube2zim.py#L47
> 
> And that's all i think...

These links do not work anymore?
Would it be too much trouble to ask for an explanation again?
I am new to python, and have a code editor installed now to try and understand what you are telling me, and to try and implement it. 
Thank You.

**Comment by kelson42** [comment]
@blueskiesoky I guess if this is not clear what needs to be done here, probably the task is simply to hard for you. One recommendation for the future: if you request help, just ask precisely what you don't understand and explain why you don't understand it... never ask for a general explanation (people have not the time to re-explain to you everything and won't answer).

**Comment by deborahlow97** [comment]
Hi, I'd like to take up this issue 😺

**Comment by kelson42** [comment]
@deborahlow97 voila!
