### ISSUE TITLE
Fullscreen is broken in Safari

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#33]
In iOS and macOS, using Safari (via kiwix-serve), video in fullscreen is not scaled-up (but appears inside a black frame).

**Comment by kelson42** [comment]
@rgaudin Do we have an upstream bug for that one?

**Comment by rgaudin** [comment]
FYI still valid on Safari `Version 13.1 (15609.1.20.111.8)`

**Comment by kelson42** [comment]
I would still like to see a link to the upstream bug here.

**Comment by kelson42** [comment]
@rgaudin I have just tried again with Safari on ipadOS 15.1 and http://library.kiwix.org/ted_en_playlist-how-perfectionism-fails-us_2021-12/A/how-to-get-better-at-the-things-you-care-about?lang=undefined and it seems to work perfectly now. Would you be able to conform please?

**Comment by rgaudin** [comment]
This ZIM has not been made with this scraper. Tested with cestpassorcier and I still have the bug.

**Comment by kelson42** [comment]
Ok, at least we know how to fix the problem... sorry if you have already answered to that questionning, but I still wonder that all this video handling is not shared code in scraperlib.

**Comment by rgaudin** [comment]
Didn't meant to confirm it works. It doesn't on macOS Safari. On iOS 15.1 iPhone, fullscreen seems to work but the video doesn't play so it's hard to be definitive.

We use a similar stack in youtube and ted but no it's not shared.

**Comment by rgaudin** [comment]
Upstream ticket https://github.com/brion/ogv.js/issues/228

**Comment by benoit74** [comment]
I just tested on Mac OS 12.7 and Safari Version 17.0 (17616.1.27.111.22, 17616), and fullscreen is working well for https://library.kiwix.org/viewer#cest-pas-sorcier_fr_all_2023-03/home.html

But there is no sound ... (I opened a separate ticket https://github.com/openzim/youtube/issues/181)

Could someone test on iOS and different Mac OS versions ?

**Comment by kelson42** [comment]
On iPadOS 16.7 fullscreen broken but sounds works.

**Comment by benoit74** [comment]
I ran another test and this time sounds is working but no video is displayed at all in Safari, no mater fullscreen or not.

**Comment by kelson42** [comment]
Pretty sure this would be fixed by just using latest scraperlib (like on TED)

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/youtube/pull/202
