### ISSUE TITLE
Videos not playing correctly on some devices

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#34]
Originat title: Controls buggy in firefox/chrome
Original content:
When screen-width is lower than 800px, video controls are buggy: play/pause doesn't work as expected but clicking on the video frame works.

----
Update: some devices are unable to play or to play correctly videos and it seems related to their viewport size and/or userAgent.
See [comment](https://github.com/openzim/youtube/issues/34#issuecomment-619896646)

**Comment by kelson42** [comment]
@rgaudin Is that a bug in Videojs?

**Comment by rgaudin** [comment]
Probably not. needs to be tested.

**Comment by rgaudin** [comment]
FYI I just rested this and:

* it works fine in Chrome now (`Version 81.0.4044.122 (Official Build) (64-bit)`)
* still have the problem with Firefox (`75.0 (64-bit)`).

**Comment by kelson42** [comment]
@rgaudin @satyamtg Do we use last version of videojs/oggjs? Should we open a bug ticket upstream?

**Comment by satyamtg** [comment]
> @rgaudin @satyamtg Do we use last version of videojs/oggjs? Should we open a bug ticket upstream?

@kelson42 currently we do not use the latest versions. We use the following -
- videojs v7.6.4 (Latest stable is 7.6.6 and latest Pre-release is 7.8.1)
- ogv.js v1.6.1 (This is the latest release)
- videojs-ogvjs v1.3.1 (This is the latest version)

**Comment by rgaudin** [comment]
OK so Satyam you may want to test that you can reproduce the issue out-of-zim with vanilla version of those lib and test if latest version fixes it.

Then, I suggest we do #84 before upgrading.

**Comment by satyamtg** [comment]
Hey @rgaudin , tested this with Firefox 75 (64-bit) on Ubuntu 19.10 and Chrome 81 (64-bit) on Ubuntu 19.10 with latest video.js 7.8.1 . It seems to work fine. I put screen-width much lower than 800px. What OS were you testing on BTW?

**Comment by kelson42** [comment]
@satyamtg Could we have a PR with latest version of videojs/oggjs merged first, before we continue that discussion? I think that would simplify it a lot.

**Comment by rgaudin** [comment]
> OK so Satyam you may want to test that you can reproduce the issue out-of-zim with vanilla version of those lib and test if latest version fixes it.

has this been done ? I believe not.

This issue is not resolved with latest videojs. but until we replicate the bug outside of the scraper with the vanilla videojs then with videojs + ogvjs we'll just but testing stuff in the dark. We need to find where the problem lies if we want to fix this.

Now testing new videosjs, I discovered that the problem isn't related to resolution but to the userAgent (or probably a combination).

With firefox, when using the preset Iphone 6/7/8, I have the problem. When switching to iPad then entering the same resolution I don't have it.

Idem on safari, when testing iphone or ipadmini preset, I have the problem, but keeping it and changing the useragent to ipad fixes it.

On my actual iPhone, it doesn't work but if I switch useragent to chrome-for-mac, it works.

I think you should now have enough information to find the root cause but please use the proposed methodology so we can identify if the problem is in `videojs`, `ogvjs`, `videojs-ogvjs`, or in our own code.

**Comment by rgaudin** [comment]
It's now OK on Firefox for mac on any resolution but the problem persists for Safari when using presets bellow iPad (even iPadmini which is same resolution) and on iOS.

Looking at the source code, both video.js and ogv.js tests the userAgent so I am once again asking that we prepare simple tests with bare videojs then videojs+ogvjs, gradually introducing the code that we use. Videojs demo do work on those devices so we should be able to identify the culprit quite easily.

**Comment by kelson42** [comment]
New check here and confirm http://library.kiwix.org/ted_en_playlist-how-to-run-a-company-like-a-vi_2021-01/A/how-to-run-a-company-with-almost-no-rules?lang=undefined  does not play with ipados 15.

**Comment by rgaudin** [comment]
@kelson42 I don't think this is related to this ticket at all. Given this ticket is already quite specific and weird, you should create another one instead.

FYI:
- behavior is different:
  - play displays a single frame then pauses
  - loading never seems to end
  - sometimes it plays but without audio
- problem appears on Big Sur Safari, which has webm support.
- other videos on that ZIM [this one for instance](http://library.kiwix.org/ted_en_playlist-how-to-run-a-company-like-a-vi_2021-01/A/why-the-best-hire-might-not-have-the-perfect-resume?lang=undefined) works fine, leaning this toward a video-specific issue.

**Comment by kelson42** [comment]
@rgaudin ok, anyway tested again with ipados 15.1 and http://library.kiwix.org/ted_en_playlist-how-to-run-a-company-like-a-vi/A/index#1 and everything works fine.

Will test with iphone on 15.1

**Comment by rgaudin** [comment]
I know this is a videojs/ogvjs related bug but it'd be wiser to test with ZIM files that were created using youtube scraper.

On Firefox, controls do work but clicking on the frame doesn't anymore. Kind of a reversed behavior.

On Safari, both works but, interestingly, I have no sound ; which is an issue I remember you mentioning.

**Comment by kelson42** [comment]
@rgaudin The "sporadic" nosound problem on iOS has been explained to me a few weeks ago. Read https://github.com/kiwix/apple/issues/379#issuecomment-966021542

**Comment by kelson42** [comment]
This ticket is outdated, problem meanwhile solved.
