### ISSUE TITLE
Fullscreen-exit is broken in firefox/chrome

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#35]
When exiting fullscreen, if the screen-width is lower than 800px, the video size and position is incorrect.

Might be related to #33

**Comment by kelson42** [comment]
@rgaudin I don't have a screen with a resolution lower than 800 with Firefox. I have one on Android, but this is a special version of Firefox. Which OS was implied here?

**Comment by satyamtg** [comment]
@rgaudin I was not able to replicate this too. I tried with both extensions on Chrome and Firefox and with the Kiwix-serve version. As I don't have a screen with width lower than 800px, I tried to make the screen smaller by resizing with Developer Tools open. All full screen exits seemed to be normal. Could you please elaborate on the device and the OS that you used?

**Comment by rgaudin** [comment]
Thanks for the updated. I was testing mostly using the developer tools and on a small-end android device that I don't have at hand anymore.

I just tested with http://mirror.download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-12.zim and couldn't reproduce it.

I suppose we can close it for now. Thanks for the test.
