### ISSUE TITLE
Stop calling yt-dlp three times in a row

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#357]
Currently, the scraper calls yt-dlp three times in a row for every video:
- once to download the video (and audio)
- once to download the thumbnail
- once to download the subtitles

video and thumbnails are cached on S3 so the call to yt-dlp might not happen if we already have populated S3 cache for this video.

In the case of a new video where cache is empty, those three calls happens.

I think we should consider to refactor the code to call yt-dlp only once, because it will probably help avoid ban by Youtube.

**Comment by kelson42** [comment]
Very supportive of this ticket considering that hitting the quotas is a very serious limitation. Anything able to improve the statu-quo without removing features should be strongly considered. Pinning.

**Comment by benoit74** [comment]
Indeed, this is a duplicate (but better written ^^)
