### ISSUE TITLE
Do we still need two tabs on home when there are multiple playlists

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#358]
Now that we have redesigned the "Videos" tab, we have directly access from this tab to all playlists. And I personally find this tab way more convenient / appealing than the "Playlists" which present only one thumbnail per playlist.

You can see a demo ZIM at https://dev.library.kiwix.org/viewer#s2underground_en_all_2024-10 or https://dev.library.kiwix.org/viewer#deus-ex-silicium_fr_all_2024-10

I suggest to simply remove the two tabs, and keep only the content of "Videos" tab as main UI.

@Popolechien @kelson42 @dan-niles WDYT?

**Comment by benoit74** [comment]
Nota : the change / redesign I'm referring to is #349 which is merged but not yet released, just to be clear ^^

**Comment by Popolechien** [comment]
Much better, yes. Regarding the two-tabs option I'm slightly in favour though if there really is a large number of playlists then that might not be super practical.

**Comment by dan-niles** [comment]
I think the `Playlist` tab is useful when you want to find a specific playlist quickly. Just for an example if I wanted to find the `Exposés` playlist in the `Deus Ex Silicium` ZIM, I'd have to scroll all the way to bottom of the 'Videos' tab, whereas in the `Playlist` tab it's pretty easy to find.

https://github.com/user-attachments/assets/4e459b95-0f0b-40d6-a8d6-f1061a07d5ea

The playlist tab gives a quick overview of the available playlists in the ZIM with a lesser scroll distance, so I think it's useful to keep.

**Comment by benoit74** [comment]
Looks like you both have same opinion, so let's keep UI as it is unless someone comes with stronger arguments, thank you!
