### ISSUE TITLE
No fullscreen support in android

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#36]
In android the fullscreen icon is grayed-out and has no effect.

Might be a [kiwix-android](https://github.com/openzim/kiwix-android) issue.

**Comment by kelson42** [comment]
Seems to be a duplicate of https://github.com/kiwix/kiwix-android/issues/44

**Comment by kelson42** [comment]
Should be fixed in the next days

**Comment by rgaudin** [comment]
Fixed
