### ISSUE TITLE
"shorts" videos resolution seems wrong (too high)

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#366]
Here is how it looks like on my iPad
![Image](https://github.com/user-attachments/assets/4bb44a82-9073-4eb8-8f87-44f903690980)

From https://library.kiwix.org/viewer#jamy_fr_all_2024-09/index.html

Bit this is how it looks like in Youtube (better because I can see the whole video)
![Image](https://github.com/user-attachments/assets/cec8a4b6-dd9e-49ab-8897-384183231e0a)

**Comment by arjitcodes** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by benoit74** [comment]
@arjitcodes please develop a plan here before submitting any PR, I'm pretty sure this is not just a UI change, the scraper probably does not yet know this video is a short, plus we might want to change the UI for shorts as mentioned in #367
