### ISSUE TITLE
Differentiate "shorts" from "normal" videos

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#367]
This is the case on Youtube, where shorts have their dedicated tab:
![Image](https://github.com/user-attachments/assets/f82f4dc5-68d0-4bbb-8b35-203cb5ee098b)

Considering that shorts work (from a user perspective) differently, I believe this would be a good improvement to stop mixing them with the other videos.

**Comment by benoit74** [comment]
Do you mean that we already adding them to the ZIM, but with the same UI than other videos?

**Comment by benoit74** [comment]
Oh yes, I just saw #366
