### ISSUE TITLE
Add `playsinline` to videoJS for proper operation on apple

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#368]
Since we want the video to play inline by default, we have to set the `playsinline` attribute on video tag.

**Comment by guptushar27** [comment]
hi i can debug this

**Comment by benoit74** [comment]
There is nothing to debug, just work to do. Do you wanna propose a PR? I've assigned the issue, please propose a PR quickly (by the end of the week at most) or I'll probably work on it, it is just a very tiny change and we would like to release it soon.

**Comment by kelson42** [comment]
@benoit74 Can we found please a way to ensure that if we have an issue around video.js, it is always fixed everywhare. I'm really surprise to see this bug, as I though it was already fixed everywhere. See https://github.com/openzim/python-scraperlib/issues/194

**Comment by benoit74** [comment]
See my last answers in https://github.com/openzim/python-scraperlib/issues/194 ; you keep complaining, we keep explaining it is a problem of tooling / procedures, not something easy to fix. And it will never be fixed everywhere quickly, at least not with our current funding.
