### ISSUE TITLE
[REGRESSION] Tags and Scraper metadata is incorrectly populated

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#369]
See https://github.com/kiwix/operations/issues/286

**Comment by kelson42** [comment]
@benoit74 The Metadata `Scraper` has also a casing problem

**Comment by dan-niles** [comment]
Fixing the casing on lines `385` and `386` in [scraper.py](https://github.com/openzim/youtube/blob/main/scraper/src/youtube2zim/scraper.py#L377-L389) should fix this issue:

https://github.com/openzim/youtube/blob/f20ac6daa3e83aac5398e5706e5cce75ad5e2134/scraper/src/youtube2zim/scraper.py#L377-L389
