### ISSUE TITLE
Exit rotation is buggy on Android

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#37]
When rotating back to portrait after landscape, video size and position is often incorrect.

Might be related to #35

**Comment by kelson42** [comment]
In my case, with the videos about Mali, I'm not able at all to get videos played in landscape mode.

**Comment by kelson42** [comment]
@rgaudin I'm not sure I fully understand the bug report here. To me (with my Google pixel 2/Android 10) it seems to work properly in fullscreen ... and I'm not sure there is something to improve without fullscreen. Could you please describe a bit more the problem so we get a chance to open a bug on kiwix-android side?

**Comment by kelson42** [comment]
@rgaudin Any feedback on this? I would like to confirm to move the issue to kiwix/kiwix-android.

**Comment by rgaudin** [comment]
Thanks for the test. Let's close it then. A lot has changed on the libkiwix and android app since that ticket was open. I was testing on 8.1 Go.
