### ISSUE TITLE
fullscreen is broken on iOS

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#39]
fullscreen doesn't work as expected on iOS:

* portrait: covers full-width but retain ratio and the rest of the page visible
* landscape: same size as portrait, rest of the page is visible
* landscape: video too large and misplaced going back to portrait after fullscreen in lanscape (see #35)
* app chrome (search bar, navigation) always visible

**Comment by kelson42** [comment]
@rgaudin Tested with 1.10.1, I confirm the problem. Does that come from the reader? We should probably make a bug report on iOS repo?

**Comment by kelson42** [comment]
This looks to be the corresponding ticket in Kiwix for iOS https://github.com/kiwix/apple/issues/80

**Comment by kelson42** [comment]
Closing because duplicate of https://github.com/kiwix/apple/issues/80
