### ISSUE TITLE
Video date is not user friendly

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#52]
On each video page, at the bottom, the date at which the video has been created (uploaded to Youtube I guess) is indicated.

Here is an example:
Jul 11, 2017, 4:34:23 PM

This information is really useful, but suffers in the way how it is displayed of two weaknesses:
* Not localized. The date is in English, the month part is not translated and the way how the date is the English one, this should be localised (depending on ZIM language)
* The precision is not adequate, I think that we should remove the time and keep the granularity at the day level.

**Comment by rgaudin** [comment]
This is the standard `medium-sized` representation of a date-time for English, so for an English speaker, that's most likely very clear.
While having the seconds here seems extra, I see no value in removing the time; a zero-cost information that might be valuable for some content.

As for the localization, it is localized. This example is for English. If you got that in a non-english ZIM, either it's a bug or the schedule didn't specify the language (let me know which ZIM it's from).

I chose to set it on the ZIM so the content is consistent but we could use a JS lib to localize it client-side if you think it's appropriate (I don't).

**Comment by kelson42** [comment]
@rgaudin This was a date in the Mali ZIM file, so I guess it is not localised properly. Libicu provides easy localisation of a date, so I guess this should be available somehow in Python directly. For the rest, useless information is bad it just make things uselessly complex to parse.

So here we should have `11 juillet 2017` in place of `Jul 11, 2017, 4:34:23 PM`. I guess you have to admit this is really easier to deal with for a user.

**Comment by rgaudin** [comment]
Thanks. I believe it's a container issue (missing locales).

I won't argue over personal preferences so let's stick with how Google does it. I have `Jul 11, 2017` in English and `Ajoutée le 11 juil. 2017` in French. Will fix.
