### ISSUE TITLE
Autoload next video

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#60]
I thought this would be a nice feature and by testing the ZIM about Mali I discovered that it was somehow working halfway. At the end of the video it seems that new one is played... but the HTML page does not change... it is buggy!

**Comment by rgaudin** [comment]
Can you be more specific. Each article page is completely independant of the others. So it should not magically start playing another video.
Can you please give instructions to reproduce ?
Also, is this a bug report (what's the bug?) or a feature request?

**Comment by kelson42** [comment]
1 - Open ZIM file about Mali
2 - Click on video about la révisoin constitutionelle
3 - Seek to the end

The video reaches the end (end the audio start with "Bonjour à tous pour cette deuxième video sur la monnaie"... the video seems stuck for a few seconds... and then somewhoe the video moves ahead too (with the right content).. but the video progress bar is still stuck at 100% and the HTML does not have changed.

**Comment by rgaudin** [comment]
OK thanks ; can you reproduce it with kiwix-serve ?

**Comment by kelson42** [comment]
Work fines with Kiwix Serve, see http://library.kiwix.org/mali-pour-les-nuls_fr_all/A/3mn_contre_la_revision_constitutionnelle.html

**Comment by rgaudin** [comment]
Then have you considered this might be an android bug?
Source code references a single video file…

**Comment by kelson42** [comment]
@rgaudin No, but I might be wrong ;)
@macgills Possible?

**Comment by macgills** [comment]
Have you looked at kiwix-serve on your phone? 
I have absolutely no idea

**Comment by kelson42** [comment]
@macgills yes, works fine. Can you reproduce the issue?

**Comment by macgills** [comment]
No, it is different. If I play the video then after the video ends it seems like it plays some audio but quickly stops
