### ISSUE TITLE
Allow to use URLs for many options like

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#63]
* Banner Image
* Profile Image

As a consequence and for the moment a few ZIM files are "broken" in the Zimfarm.

Like:
* https://farm.openzim.org/recipes/skin-of-color-society_en_all (no ZIM favicon)

**Comment by kelson42** [comment]
@rgaudin You confirm please this is not possible for the moment?

**Comment by rgaudin** [comment]
The two options you mention already support both filename and URLs.

Given the URL you provided doesn't mentions any of those options, I don't see your connexion with the favicon…

If there's a favicon issue, please open a separate ticket. If you'd want the path and URL support be mentioned in the help, a PR is welcome :)
