### ISSUE TITLE
Video lacks sound

### ISSUE THREAD

**Issue by HAKSOAT** [openzim/youtube#70]
I've been trying to run the code and download videos, which I was able to do successfully. However, I can't seem to hear anything from the videos. Is this a normal thing?

I ran:

`python3 -m youtube2zim --type playlist --id "PLQVvvaa0QuDdc2k5dwtDTyT9aCja0on8j" --api-key <appi-key> --name test --no-zim --output ../test`

Opened the `home.html` page and played the videos, but I can't hear anything; even when I play the videos directly from a video player. 

I face the same issue when I play videos here: [http://library.kiwix.org/skin-of-color-society_en_all/A/home.html#1](http://library.kiwix.org/skin-of-color-society_en_all/A/home.html#1
)

**Comment by kelson42** [comment]
@HAKSOAT Do you have the same problem with a ZIM?

**Comment by rgaudin** [comment]
Thank you @HAKSOAT for this report It looks like we have a regression on either youtube or youtube-dl side as even those which used to work have no sound anymore.

Investingating it now

**Comment by rgaudin** [comment]
To be more clear, it seems that requesting `webm` format doesn't return us a file with audio anymore.

**Comment by kelson42** [comment]
@rgaudin wow!
@HAKSOAT Forget about my comment then.

**Comment by HAKSOAT** [comment]
Hmmmm. Okay. In that case, I think `webm` shouldn't be the default any more.

**Comment by rgaudin** [comment]
Yeah well I think we'll have to be smarter and cherry-pick the format. At least for those I tried, Youtube doesn't seem to provide audio+video webm at all.

```
youtube-dl -F yCZoYfNNbQk |grep webm
251          webm       audio only DASH audio   99k , webm_dash container, opus @160k (48000Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 25fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 25fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 25fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 25fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 25fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 25fps, video only
```

**Comment by HAKSOAT** [comment]
It doesn't. I've checked on different links here as well.

**Comment by rgaudin** [comment]
OK, well thank you very much for that important report! @kelson42, I'm disabling all youtube recipes in the zimfarm and working on a fix now

**Comment by HAKSOAT** [comment]
`youtube-dl -F 'http://www.youtube.com/watch?v=wqEsTPaUZF0' | grep webm`

> 249          webm       audio only tiny   55k , opus @ 50k (48000Hz), 9.86MiB
250          webm       audio only tiny   74k , opus @ 70k (48000Hz), 12.65MiB
251          webm       audio only tiny  145k , opus @160k (48000Hz), 24.32MiB
278          webm       256x144    144p  134k , webm container, vp9, 30fps, video only, 17.70MiB
242          webm       426x240    240p  205k , vp9, 30fps, video only, 22.79MiB
243          webm       640x360    360p  377k , vp9, 30fps, video only, 50.51MiB
244          webm       854x480    480p  719k , vp9, 30fps, video only, 91.37MiB
247          webm       1280x720   720p 1366k , vp9, 30fps, video only, 119.10MiB
248          webm       1920x1080  1080p 2310k , vp9, 30fps, video only, 152.75MiB


I think this sample maxes out the available download options.
