### ISSUE TITLE
name argument should not be required when using no-zim argument

### ISSUE THREAD

**Issue by nabinkhadka** [openzim/youtube#78]
With `--no-zim` argument, it should not throw following error:

```
youtube2zim: error: the following arguments are required: --name
```

**Comment by kelson42** [comment]
@rgaudin I'm in favour to remove this option anyway. OK for you?

**Comment by rgaudin** [comment]
Well there's more to it. Regarding this issue, the doc says that `--name` is mandatory so it's not a bug per say but we don't use that variable in this case so it's annoying to request it.

As for the future, I've been thinking about it and we should put some thinking into how we want to deal with this (for all scrapers). pylibzim allows us to stream into the ZIM file which will be a big performance and resource boost but doing this it removes the ability to locally prepare an archive and ZIM it.
While prod doesn't care about this, dev should be easier, not harder with that new tool so we need to think about it… but it's a cross-scraper question.

**Comment by kelson42** [comment]
@rgaudin To me, the solution is that `zimdump` should work properly and Python devs should not debug the libzim but there own code (so no really need to know what is in the ZIM file).

**Comment by dattaz** [comment]
I'm not in favour of removing `--no-zim` since people may want to use our scrappers and HTML generation without having a zim file at the end (archiving, put online there own "backup" of content, maybe IPFS stuffs etc...).

**Comment by rgaudin** [comment]
@dattaz that's what I meant by we need to think about it. Right now it's a mandatory step but with the use of pylibzim, it will because a separate feature.

**Comment by kelson42** [comment]
> I'm not in favour of removing `--no-zim` since people may want to use our scrappers and HTML generation without having a zim file at the end (archiving, put online there own "backup" of content, maybe IPFS stuffs etc...).

They should make the ZIM file and then use `zimdump -D`.  We are currently securing that this works fine. This shoudl give the same result and avoiding us to matain this kind of feature for all our scrapers.

**Comment by kelson42** [comment]
@dattaz Your opinion/feedback matters here, as we are about to remove the "no-zim" options in all our scrapers to simplify them (and because maintaining them - in a context where libzim bindings are used - is expensive).

Our effort to have a perfectly working `zimdump -D` comes to the end, see https://github.com/openzim/zim-tools/issues?q=is%3Aissue+is%3Aopen+label%3AIPFS. I would as well really welcome soon a fuse driver for ZIM files.

In two words: it is important to me that key developers are aligned on this.

**Comment by rgaudin** [comment]
It's important that the ones writing the scraper have a comfortable environment. That's why I think we can't rush this out. We need to:

* get our hand on the pylibzim
* find a good workflow with the new paradigm
* get rid of what's now useless

> in this order. otherwise we'll have uncomfortable tools leading to delays in fixing/improving the code base.

**Comment by kelson42** [comment]
@rgaudin It is important to me that features are primarly made for users and not developers. I expect developers to build anything needed by them to get the job done. But I would consider carefully anything having an impact on end-users.

Considering this specific ticket, there is no hurry as youtube2zim does not use python-libzim so far... but I guess this will arrive in the next weeks. But I don't want us investing time on keeping this feature working as it is currently, this is just not worth it.

Could you please open one or many tickets if you think the move to python-libzim create new challenges for developers? The discussion is important but I would like to scope it properly.
