### ISSUE TITLE
Video sound disjointed on Kiwix-Desktop

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#87]
Reported in https://github.com/kiwix/kiwix-desktop/issues/425
Seems to be related to the sampling rate change introduced in 58748bee394c6.

Testing with a revert of this…

**Comment by satyamtg** [comment]
@rgaudin I agree with you as I tested on videos which were not  re-encoded in low quality and couldn't find this issue.

**Comment by rgaudin** [comment]
It's not related to that sampling argument. Just generated a new ZIM with and without it and I am having the issue with both.

I tested with a custom playlist `PL2DQc1tA1YU2sJzyCSjmL8CxG9rN-4wD_` which includes `Y1W67I0Gp8Y` that is affected. Original content being 48Khz, I though it would fix it but it doesn't.

**Comment by rgaudin** [comment]
OK another change that happened in-between is the fact that we don't get video+audio files from youtube anymore and so what we request from youtube (via youtube-dl) is different.
So we are not converting the same source as before, and we cannot go back to that state.

That would imply that this _glitch_ triggering that issue on kiwix-desktop comes from the muxing of video and audio streams… but it doesn't concern all videos neither.

I suppose there's no upstream (youtube-dl) bug as the bug is not present on regular video players nor browsers…

**Comment by rgaudin** [comment]
Closing this as WONTFIX as there's nothing we can reasonably do: [compatibility](/openzim/youtube/wiki/Compatibility) shows it's a kiwix-desktop issue among a couple other video-related issues. Will update bug there with the information we gathered.
