### ISSUE TITLE
Should we improve video quality?

### ISSUE THREAD

**Issue by rgaudin** [openzim/youtube#90]
I am not very satisfied with the video quality of the ZIM files we serve, especially given we provide a single flavour. AFAIK, we have not received any complain about it though (@Popolechien can you confirm) but it bugs me a little.

I also know that the current compression settings have been selected years ago so I was wondering if we should update it a bit, **at the expense of bigger ZIM files, of course**.

I wrote a little script to test a couple other presets and compare the output with the current encoding.

You can see the result in [report.html](http://tmp.kiwix.org/youtube/report.html).
I am attaching a screenshot in case this goes away…
![Comparison](https://user-images.githubusercontent.com/57929/80358224-99b6e580-886b-11ea-9f84-23b4a5d3159d.png)

As you can see, I randomly selected sample videos from the channels we scrape and compressed all of them with 3 different presets:

* `previous`: the one we currently use in the scraper. HVGA resolution (480x270) with very aggressive quality range (30-42) and a 300k bitrate average (but with a weird 1000k bufsize).
* `240p`: 240p resolution (426x240) with good quality range (16-26) but a constant video bitrate of 128k and audio bitrate of 48k.
* `360p`: 360p resolution (640x360), similar to 240p but with 384k bitrate.

Unfortunately, the `240p` while reasonably bigger than `previous` **is not significantly better**. It works best on animations and texts, but otherwise barely noticeable.

The `360p` is way better but also way bigger. 

I though it could easily demonstrate better quality without major size impact but could not. Still, we may want to tweak the converter in the future and I think that script is a good way to try and compare.

@kelson42 should I push it here in a `contrib` folder or should it be pushed somewhere else?

**Comment by kelson42** [comment]
@rgaudin Yes, please put the tool in contrib. This is a valuable script.

**Comment by rgaudin** [comment]
Script has been pushed ; @Popolechien any feedback from youtube users?

**Comment by Popolechien** [comment]
Only this one (from Hotspot user): 
"Ted talks - not the most user friendly landing page (thumbnails are stretched, just having a long scroll list is not the most easy visual to browse videos, making some basic categorisations here would be good). It's good that you can scroll for different languages but I had issues making the page update with my language selection."
